### ISSUE TITLE
Play .mp3 files

### ISSUE THREAD

**Issue by andrius-k** [freshplanet/ANE-Video#4]
When I play mp3 file using this player, it starts playing but in a second all app crashes. I'm testing on iphone 4. Is it not compatible with music files or I'm doing something wrong??
Thanks in advance :)

**Comment by dornad** [comment]
ANE-Video is designed and tested for video playback. 

While MP3 files are playable in MPMoviePlayerViewController on iOS, our current implementation doesn't have the logic to handle MP3 format

You are more than welcome to fork our project and add MP3 audio support.

**Comment by andrius-k** [comment]
Thanks allot for the info :)
